#!/usr/bin/env python3
"""Generate the single-file, Mathlib-only Lean4Web edition from the `Qex94` modules.

The FC statement module only uses `import FormalConjecturesUtil` for the `answer( )`
syntax, which the generated file replaces by a local macro with the same meaning
(`answer(t)` elaborates to `t`). Each module is wrapped in its own `section` so that its
`open` and `set_option` commands do not leak into later modules.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ORDER = ["Statement", "Basic", "Link", "Shadow", "Abstract", "Lower", "Main",
         "PurityFacts", "Abstract10", "SignSums", "Main10", "KK11", "Abstract11", "Main11"]
VERSION = sys.argv[1] if len(sys.argv) > 1 else "4.34.0"

HEADER = f'''import Mathlib

set_option autoImplicit false

/-!
# `Qex 9 4 = 112`, `Qex 10 5 ≤ 208`, `Qex 11 5 ≤ 422`: standalone Lean4Web edition

Mathlib-only edition of the proof in `lean/`. The definitions are copied verbatim from the
Formal Conjectures statement file `FClikeLean/QuantumExtremalNumber.lean` (FC metadata
attributes omitted). Generated by `lean/scripts/make_lean4web.py`; do not edit by hand.
-/

-- In Formal Conjectures, `answer(t)` elaborates to `t` for an explicit answer `t`.
-- This local macro supplies the same surface syntax.
macro "answer(" t:term ")" : term => `($t)

-- Checked with Lean and Mathlib v4.34.0 and v4.35.0-rc3.
#eval Lean.versionString
'''

FOOTER = '''
#print axioms QuantumExtremalNumber.qex_nine
#print axioms QuantumExtremalNumber.qex_ten.variants.upper
#print axioms QuantumExtremalNumber.qex_eleven.variants.upper
'''

def body(name: str) -> str:
    text = (ROOT / "Qex94" / f"{name}.lean").read_text()
    lines = [l for l in text.splitlines() if not re.match(r"^import\s", l)]
    return "\n".join(lines).strip("\n")

parts = [HEADER]
for name in ORDER:
    parts.append(f"\n/- ## Module `Qex94.{name}` -/\n\nsection Module{name}\n\n{body(name)}\n\nend Module{name}\n")
parts.append(FOOTER)
out = ROOT.parent / "lean4web" / "Qex94Lean4Web.lean"
if not out.parent.exists():
    out = ROOT.parent / "qex94-l4w" / "Qex94Lean4Web.lean"
if len(sys.argv) > 2:
    out = pathlib.Path(sys.argv[2])
out.write_text("".join(parts))
print(f"wrote {out} ({sum(1 for _ in out.open())} lines)")
